platform :ios, "7.0"
#pod 'PPiAwesomeButton', :git => 'https://github.com/VadimYushchenko/PPiAwesomeButton.git'
pod 'PPiAwesomeButton', :path => '/Users/vadimyushchenko/Projects/Objective-c/PPiAwesomeButton/'